subtask: 'pose_as_state'  # 'gnn_test'  # 'graph2vec_test', 'pose_as_state'
env_file: "/home/sdur/Planning/Codes/base_pose_optimization/isaac_envs/task_square.usd"
mdp:
  gamma: 1
  horizon: 1
  reward:
    task_success: 100000
  navigation:
    max_tran_speed: 0.3
    max_rot_speed: 0.3
  manipulation:
    max_rot_speed: 0.25
  table_dimensions:
    x_min: -0.75 # -0.4
    x_max:  0.75 #  0.4
    y_min: -0.75 # -1.0
    y_max:  0.75 #  1.0
  safe_dist_from_table: 0.1
  max_dist_from_table: 0.3
  obj_safety_distance: 0.1
  render: False
train:
  initial_replay_size: 4500 # 1500
  max_replay_size: 100000
  batch_size: 4096 #128 #4096 # 128
  n_features: 256  # 32 # 256 # 128
  warmup_transitions: 4500 # 1500
  tau: 0.005 # 0.005
  n_steps_per_fit: 1
  lr_alpha: 3e-4 # 3e-4
  lr_actor: 3e-4
  lr_critic: 3e-4
  target_entropy: None # inside
  n_epochs: 2001
  n_steps_train: 4500
  n_steps_test: 1500
  save_dir: '/home/sdur/Planning/Data/FCT4/96'
  use_curricullum: False
  pre_trained_agent_dir: '/home/sdur/Planning/Data/FCT4/54'
  pre_trained_agent_name: 'optimize_base_pose_SAC_epoch_400'
  use_replay_buffer_prior: False
  replay_buffer_prior_path: '/home/sdur/Planning/Data/FCT4/replay_buffer/replay_buffer_best.npz'
test:
  save_dir: '/home/sdur/Planning/Data/FCT4/96'
  epoch_no: 40
  n_episodes: 5000
  n_steps: 5000
  save_data: True

