task:
  env_file: "/home/sdur/Planning/Codes/pre-grasp-approaching/isaac_envs/task_square.usd"
  mdp:
    gamma: 0.95
    horizon: 25
    max_dist: 0.1
    max_base_turn: 0.26179938779 #pi/12
    max_shoulder_pan_turn: 0.26179938779 #pi/12
    max_shoulder_lift_turn: 0.26179938779 #pi/12
    max_elbow_turn: 0.26179938779 #pi/12
    render: False
  train:
    initial_replay_size: 3000
    max_replay_size: 100000
    batch_size: 256
    n_features: 128
    warmup_transitions: 5000
    tau: 0.005
    n_steps_per_fit: 1
    lr_alpha: 3e-4
    lr_actor: 3e-4
    lr_critic: 3e-4
    n_epochs: 2001
    n_steps_train: 4500
    n_steps_test: 1500
    save_dir: '/home/sdur/Planning/Data/FCT4/96'
    use_layers: False
  test:
    save_dir: '/home/sdur/Planning/Data/FCT4/96'
    epoch_no: 40
    n_episodes: 5000
    n_steps: 5000
    save_data: False

